FROM debian as set_secret

ARG SECRET_STRING
RUN echo "SECRET_STRING=${SECRET_STRING}" >/tmp/secrets.txt

FROM debian

COPY --from=set_secret /tmp/secrets.txt /tmp/secrets.txt
RUN . /tmp/secrets.txt \
 && echo "意図的に秘密の文字列を出力します" \
 && echo " ${SECRET_STRING} が秘密の文字列です。出力されなければなりません"
